version: "3"

services:
  server:
    image: node:10.3.0
    ports:
      - 1337:1337
    volumes:
      - ./:/code
    links:
      - nodeosd
    working_dir: /code
    command: /bin/bash -c "npm install && node main.js"
        
  nodeosd:
    image: eosio/eos-dev:v1.0.1
    command: /opt/eosio/bin/nodeosd.sh -e --contracts-console
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ./data/nodeos-data-volume:/opt/eosio/bin/data-dir

  keosd:
    image: eosio/eos-dev:v1.0.1
    command: /opt/eosio/bin/keosd
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - ./data/keosd-data-volume:/opt/eosio/bin/data-dir
      - ./contracts:/contracts
      - ./data/eosio-wallet:/root/eosio-wallet
